[package]
name = "token-signer"
version = "0.10.2"
description = "Sign transactions by owning a token"
homepage = "https://goki.so"
repository = "https://github.com/GokiProtocol/goki"
authors = ["Goki Rajesh <goki@goki.so>"]
license = "AGPL-3.0"
edition = "2021"
keywords = ["solana", "goki", "multisig", "anchor"]

[lib]
crate-type = ["cdylib", "lib"]
name = "token_signer"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "^0.24.2"
anchor-spl = "^0.24.2"
vipers = "^2.0"
